[package]
name = "dora-mistral-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cuda = ["mistralrs/cuda"]
cudnn = ["mistralrs/cudnn"]
flash-attn = ["cuda", "mistralrs/flash-attn"]

[dependencies]
dora-node-api = { workspace = true }
tokio = { version = "1.36.0", features = ["full"] }
eyre = "0.6.8"

[target.'cfg( target_os = "macos" )'.dependencies]
mistralrs = { git = "https://github.com/EricLBuehler/mistral.rs.git", features = [
    "metal",
    "accelerate",
] }

[target.'cfg( target_os = "linux" )'.dependencies]
mistralrs = { git = "https://github.com/EricLBuehler/mistral.rs.git" }
