[build-system]
requires = ["maturin>=0.13.2"]
build-backend = "maturin"

[project]
name = "dora-kit-car"
dynamic = ["version"]
authors = [{ name = "Leon", email = "echo_ai@foxmail.com" }]
description = "Dora Node for dora kit car"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"

scripts = { "dora-kit-car" = "dora_kit_car:py_main" }

[tool.maturin]
features = ["python", "pyo3/extension-module"]

[tool.ruff.lint]
extend-select = [
  "D",   # pydocstyle
  "UP",  # Ruff's UP rule
  "PERF" # Ruff's PERF rule
]