[build-system]
requires = ["maturin>=0.13.2"]
build-backend = "maturin"

[project]
name = "dora-kit-car"
version = "0.3.8"
authors = [{ name = "Leon", email = "echo_ai@foxmail.com" }]
description = "Dora Node for dora kit car"
readme = "README.md"

scripts = { "dora-kit-car" = "dora_kit_car:py_main" }

[tool.maturin]
features = ["python", "pyo3/extension-module"]
