[package]
name = "dora-operator-api-types"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { version = "45.0.0", features = ["ffi"] }

[dependencies.safer-ffi]
version = "0.1.2"
features = ["headers"]
