[package]
name = "dora-operator-api-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.safer-ffi]
git = "https://github.com/getditto/safer_ffi.git"
features = ["proc_macros", "headers"]
