[package]
name = "dora-rerun"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
python = ["pyo3"]

[dependencies]
dora-node-api = { workspace = true, features = ["tracing"] }
eyre = "0.6.8"
tokio = { version = "1.24.2", features = ["rt"] }
rerun = { version = "0.19.0", features = ["web_viewer", "image"] }
ndarray = "0.15.6"
k = "0.32"
pyo3 = { workspace = true, features = [
    "extension-module",
    "abi3",
], optional = true }


[lib]
name = "dora_rerun"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]
