[workspace]
members = ["cargo:binaries/cli"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
# Path that installers should place binaries in
install-path = "~/.dora/bin"
# Whether to install an updater program
install-updater = false
# Build only the required packages, and individually
precise-builds = true
# Whether to consider the binaries in a package for distribution (defaults true)
dist = false
# Whether dist should create a Github Release or use an existing draft
create-release = false

[dist.github-custom-runners]
x86_64-pc-windows-msvc = "windows-2022"
x86_64-unknown-linux-gnu = "ubuntu-22.04"

[dist.bin-aliases]
dora-cli = ["dora"]
