[package]
name = "communication-layer-request-reply"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait = "0.1.89"
bincode = "1.3.3"
postcard = { version = "1.1.3", features = ["use-std"] }
serde = "1.0.228"
shared-memory-server = { workspace = true }
tokio = { version = "1.49.0", features = ["io-util"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
