[package]
name = "dora-operator-api"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
description = "Rust API implemetation for Dora Operator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-operator-api-macros = { path = "macros" }
dora-operator-api-types = { path = "types" }
