[project]
name = "opencv-plot"
version = "0.3.10"
authors = [
    { name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" },
    { name = "Enzo Le Van", email = "dev@enzo-le-van.fr" },
]
description = "Dora Node for plotting text and bbox on image with OpenCV"


requires-python = ">=3.8"

dependencies = ["dora-rs >= 0.3.10", "numpy < 2.0.0", "opencv-python >= 4.1.1"]

[dependency-groups]
dev = ["pytest >=8.1.1", "ruff >=0.9.1"]

[project.scripts]
opencv-plot = "opencv_plot.main:main"
