[package]
name = "rust-dataflow-url-example-sink"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { workspace = true, features = ["zenoh"] }
eyre = "0.6.8"
