[package]
name = "dora-schema-macro"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
communication-layer-request-reply.workspace = true
convert_case = "0.10.0"
proc-macro2 = "1"
quote = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
syn = { version = "2", features = ["full", "parsing"] }
