[package]
name = "cxx-dataflow-example-operator-rust-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cxx = "1.0.73"
dora-operator-api = { version = "0.1.0", path = "../../../apis/rust/operator" }
eyre = "0.6.8"
futures = "0.3.21"
rand = "0.8.5"
tokio = { version = "1.20.1", features = ["rt", "macros"] }

[build-dependencies]
cxx-build = "1.0.73"
