[tool.poetry]
name = "dora-pyorbbecksdk"
version = "0.3.6"
authors = ["Haixuan Xavier Tao <tao.xavier@outlook.com>"]
description = "Dora Node for capturing video with PyOrbbeck SDK"
readme = "README.md"

packages = [{ include = "dora_pyorbbecksdk" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
python = "^3.7"
numpy = "< 2.0.0"
opencv-python = ">= 4.1.1"


[tool.poetry.scripts]
dora-pyorbbecksdk = "dora_pyorbbecksdk.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
