[build-system]
requires = ["maturin>=0.13.2"]
build-backend = "maturin"

[project]
name = "dora-rs"
# Install pyarrow at the same time of dora-rs
dependencies = ['pyarrow']

[tool.maturin]
features = ["pyo3/extension-module"]
