[tool.poetry]
name = "llama-factory-recorder"
version = "0.3.7"
authors = [
    "Haixuan Xavier Tao <tao.xavier@outlook.com>",
    "Enzo Le Van <dev@enzo-le-van.fr>",
]
description = "Dora Node for VLM"
readme = "README.md"

packages = [{ include = "llama_factory_recorder" }]

[tool.poetry.dependencies]
python = "^3.7"
dora-rs = "^0.3.6"
pillow = "^10.4.0"
opencv-python = ">= 4.1.1"

[tool.poetry.scripts]
llama-factory-recorder = "llama_factory_recorder.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
