[project]
name = "llama-factory-recorder"
version = "0.3.11"
authors = [
  { name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" },
  { name = "Enzo Le Van", email = "dev@enzo-le-van.fr" },
]
license = { file = "MIT" }
description = "Dora Node for VLM"

requires-python = ">=3.8"

dependencies = [
  "dora-rs >= 0.3.9",
  "pillow >= 10.4.0",
  "opencv-python >= 4.1.1",
]

[dependency-groups]
dev = ["pytest >=8.1.1", "ruff >=0.9.1"]

[project.scripts]
llama-factory-recorder = "llama_factory_recorder.main:main"

[tool.ruff.lint]
extend-select = [
  "D",    # pydocstyle
  "UP",   # Ruff's UP rule
  "PERF", # Ruff's PERF rule
  "RET",  # Ruff's RET rule
  "RSE",  # Ruff's RSE rule
  "NPY",  # Ruff's NPY rule
  "N",    # Ruff's N rule
  "I",    # Ruff's I rule
]
