[package]
name = "dora-node-api-c"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
eyre = "0.6.8"
flume = "0.10.14"

[dependencies.dora-node-api]
default-features = false
features = ["zenoh"]
path = "../../rust/node"
