[package]
name = "communication-layer-pub-sub"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["zenoh"]
zenoh = ["dep:zenoh"]

[dependencies]
zenoh = { version = "1.3.0", optional = true, features = ["transport_tcp"] }
flume = "0.10"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
