[package]
name = "rust-dataflow-example-sink"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { version = "0.1.1", path = "../../../apis/rust/node" }
eyre = "0.6.8"
