[package]
name = "dora-node-api"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["tracing"]
tracing = ["dep:dora-tracing"]

[dependencies]
dora-core = { workspace = true }
dora-message = { workspace = true }
shared-memory-server = { workspace = true }
eyre = "0.6.7"
serde_yaml = "0.8.23"
tracing = "0.1.33"
flume = "0.10.14"
bincode = "1.3.3"
shared_memory_extended = "0.13.0"
dora-tracing = { workspace = true, optional = true }
arrow = { workspace = true }
futures = "0.3.28"
futures-concurrency = "7.3.0"
futures-timer = "3.0.2"
dora-arrow-convert = { workspace = true }
aligned-vec = "0.5.0"
serde_json = "1.0.86"

[dev-dependencies]
tokio = { version = "1.24.2", features = ["rt"] }
