[package]
name = "dora-node-api"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true

[features]
default = ["tracing"]
tracing = ["dep:dora-tracing"]

[dependencies]
dora-core = { workspace = true }
shared-memory-server = { workspace = true }
eyre = "0.6.7"
once_cell = "1.13.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
serde_json = "1.0.89"
thiserror = "1.0.30"
tracing = "0.1.33"
flume = "0.10.14"
uuid = { version = "1.1.2", features = ["v4"] }
capnp = "0.14.11"
bincode = "1.3.3"
shared_memory = "0.12.0"
dora-tracing = { workspace = true, optional = true }
arrow = "35.0.0"
futures = "0.3.28"
futures-concurrency = "7.3.0"

[dev-dependencies]
tokio = { version = "1.24.2", features = ["rt"] }
