[tool.poetry]
name = "dora-keyboard"
version = "0.3.7"
authors = [
    "Haixuan Xavier Tao <tao.xavier@outlook.com>",
    "Enzo Le Van <dev@enzo-le-van.fr>",
]
description = "Dora dora-keyboard"
license = "MIT License"
homepage = "https://github.com/dora-rs/dora.git"
documentation = "https://github.com/dora-rs/dora/blob/main/node-hub/dora-keyboard/README.md"
readme = "README.md"
packages = [{ include = "dora_keyboard" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
pyarrow = ">= 5.0.0"
pynput = "^1.6.0"
python = "^3.7"

[tool.poetry.scripts]
dora-keyboard = "dora_keyboard.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
