[tool.poetry]
name = "pyarrow-sender"
version = "0.3.7"
authors = [
    "Haixuan Xavier Tao <tao.xavier@outlook.com>",
    "Enzo Le Van <dev@enzo-le-van.fr>",
]
description = "Dora pyarrow Sender"
license = "MIT License"
homepage = "https://github.com/dora-rs/dora.git"
documentation = "https://github.com/dora-rs/dora/blob/main/node-hub/pyarrow-sender/README.md"
readme = "README.md"
packages = [{ include = "pyarrow_sender" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
pyarrow = ">= 5.0.0"
python = "^3.7"

[tool.poetry.scripts]
pyarrow-sender = "pyarrow_sender.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
