[package]
name = "dora-message"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# Building capnp schema script is disabled by default as it requires to install capnp.
# To change the schema install capnp at: https://capnproto.org/install.html
# And comment the following to build the new schema.
build = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capnp = { version = "0.14.6", features = ["unaligned"] }
uhlc = "0.5.1"
serde = { version = "1.0.136", features = ["derive"] }

[build-dependencies]
capnpc = "0.14"
