[package]
name = "dora-message"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
build = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capnp = { version = "0.14.6", features = ["unaligned"] }
uhlc = "0.5.1"

[build-dependencies]
capnpc = "0.14"
