[package]
name = "dora-rav1e"
edition = "2021"
version = "0.3.11+fix1"
description.workspace = true
documentation.workspace = true
license = "BSD-2-Clause"
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
python = ["pyo3"]

[dependencies]
rav1e = { version = "0.7.1", features = ["serialize"] }
dora-node-api = { workspace = true, features = ["tracing"] }
eyre = "0.6.8"
log = "0.4"
bytemuck = "1.20"
pyo3 = { workspace = true, features = [
    "extension-module",
    "abi3",
    "eyre",
    "generate-import-lib",
], optional = true }
avif-serialize = "0.8.3"


[lib]
name = "dora_rav1e"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]
