[package]
name = "shared-memory-server"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
serde = { version = "1.0.152", features = ["derive"] }
shared_memory_extended = "0.13.0"
# TODO use upstream release once https://github.com/elast0ny/raw_sync-rs/pull/29 is merged
# Current fix, use personally pushed `raw_sync_2` version.
raw_sync_2 = "0.1.5"
bincode = "1.3.3"
tracing = "0.1.37"
