[package]
name = "dora-coordinator"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
dora-node-api = { path = "../../apis/rust/node" }
eyre = "0.6.7"
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
tokio = { version = "1.23.1", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["io-util"] }
tokio-util = { version = "0.7.1", features = ["codec"] }
clap = { version = "3.1.8", features = ["derive"] }
uuid = { version = "1.2.1" }
time = "0.3.9"
rand = "0.8.5"
dora-core = { workspace = true }
dora-message = { path = "../../libraries/message" }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
futures-concurrency = "5.0.1"
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", rev = "79a136e4fd90b11ff5d775ced981af53c4f1071b" }
serde_json = "1.0.86"
dora-download = { path = "../../libraries/extensions/download" }
which = "4.3.0"
communication-layer-request-reply = { path = "../../libraries/communication-layer/request-reply" }
thiserror = "1.0.37"
