[package]
name = "dora-download"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
reqwest = { version = "0.12.4", default-features = false, features = [
    "rustls-tls",
] }
tokio = { version = "1.24.2", features = ["fs"] }
tracing = "0.1.36"
