[package]
name = "dora-download"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
tempfile = "3.3.0"
reqwest = "0.11.12"
tokio = { version = "1.17.0" }
tracing = "0.1.36"
