[project]
name = "dora-pyrealsense"
version = "0.3.9-rc1"
authors = [{ name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com" }]
description = "Dora Node for capturing video with Pyrealsense"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "dora-rs >= 0.3.6",
    "numpy < 2.0.0",
    "opencv-python >= 4.1.1",
    "pyrealsense2-macosx >= 2.54.2; sys_platform == 'darwin'",
    "pyrealsense2 == 2.54.1.5216; sys_platform == 'linux'",
    "pyrealsense2 == 2.54.1.5216; sys_platform == 'windows'",
]
[dependency-groups]
dev = ["pytest >=8.1.1", "ruff >=0.9.1"]

[project.scripts]
dora-pyrealsense = "dora_pyrealsense.main:main"
