[tool.poetry]
name = "ultralytics-yolo"
version = "0.3.6-rc0"
authors = [
    "Haixuan Xavier Tao <tao.xavier@outlook.com>",
    "Enzo Le Van <dev@enzo-le-van.fr>",
]
description = "Dora Node for object detection with Ultralytics YOLOv8"
readme = "README.md"

packages = [{ include = "ultralytics_yolo" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6rc0"
numpy = "< 2.0.0"
ultralytics = "<= 8.2.52"

[tool.poetry.scripts]
ultralytics-yolo = "ultralytics_yolo.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
