[package]
name = "dora-operator-api-c"
version.workspace = true
edition = "2021"
description = "C API implementation for Dora Operator"
documentation.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
dora-operator-api-types = { workspace = true }

[build-dependencies]
dora-operator-api-types = { workspace = true }
