[package]
name = "dora-runtime"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
dora-node-api = { path = "../../apis/rust/node", default-features = false, features = [
    "zenoh",
    "iceoryx",
] }
dora-operator-api-python = { path = "../../apis/python/operator" }
dora-operator-api-types = { path = "../../apis/rust/operator/types" }
dora-core = { version = "0.1.0", path = "../../libraries/core" }
dora-tracing = { path = "../../libraries/extensions/telemetry/tracing", optional = true }
dora-metrics = { path = "../../libraries/extensions/telemetry/metrics", optional = true }
opentelemetry = { version = "0.17", features = [
    "rt-tokio",
    "metrics",
], optional = true }
opentelemetry-system-metrics = { version = "0.1.1", optional = true }
eyre = "0.6.8"
futures = "0.3.21"
futures-concurrency = "2.0.3"
libloading = "0.7.3"
serde_yaml = "0.8.23"
tokio = { version = "1.17.0", features = ["full"] }
tokio-stream = "0.1.8"
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git" }
zenoh-config = { git = "https://github.com/eclipse-zenoh/zenoh.git" }
fern = "0.6.1"
pyo3 = { version = "0.16.5", features = ["auto-initialize", "eyre"] }
flume = "0.10.14"
dora-message = { path = "../../libraries/message" }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
http = "0.2.8"
tempfile = "3.3.0"
reqwest = "0.11.12"

[features]
tracing = ["opentelemetry", "dora-tracing"]
metrics = ["opentelemetry", "opentelemetry-system-metrics", "dora-metrics"]
