[package]
name = "dora-runtime"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { workspace = true, default-features = false }
dora-operator-api-python = { workspace = true }
dora-operator-api-types = { workspace = true }
dora-core = { workspace = true }
dora-tracing = { workspace = true, optional = true }
dora-metrics = { workspace = true, optional = true }
opentelemetry = { version = "0.17", features = [
    "rt-tokio",
    "metrics",
], optional = true }
opentelemetry-system-metrics = { version = "0.1.1", optional = true }
eyre = "0.6.8"
futures = "0.3.21"
futures-concurrency = "7.1.0"
libloading = "0.7.3"
serde_yaml = "0.8.23"
tokio = { version = "1.24.2", features = ["full"] }
tokio-stream = "0.1.8"
# pyo3-abi3 flag allow simpler linking. See: https://pyo3.rs/v0.13.2/building_and_distribution.html
pyo3 = { version = "0.16", features = ["eyre", "abi3-py37"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
dora-download = { workspace = true }
flume = "0.10.14"

[features]
default = ["tracing"]
tracing = ["dora-tracing"]
telemetry = ["tracing", "opentelemetry", "dora-tracing/telemetry"]
metrics = ["opentelemetry", "opentelemetry-system-metrics", "dora-metrics"]
