[package]
name = "dora-operator-api-macros"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Rust API Macros for Dora Operator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.81", features = ["full"] }
quote = "1.0.10"
proc-macro2 = "1.0.32"

[dev-dependencies]
dora-operator-api = { path = ".." }
dora-operator-api-types = { path = "../types" }
