[package]
name = "dora-object-to-pose"
version = "0.3.11"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { workspace = true }
eyre = "0.6.8"
pyo3 = { workspace = true, features = [
    "extension-module",
    "abi3",
    "eyre",
    "generate-import-lib",
], optional = true }

[features]
default = []
python = ["pyo3"]


[lib]
name = "dora_object_to_pose"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]
