[build-system]
requires = ["maturin>=0.13.2"]
build-backend = "maturin"

[project]
name = "dora-object-to-pose"
dynamic = ["version"]
license = { text = "MIT" }
requires-python = ">=3.8"

dependencies = ["maturin>=1.8.2"]

scripts = { "dora-object-to-pose" = "dora_object_to_pose:py_main" }

[tool.maturin]
features = ["python", "pyo3/extension-module"]

[tool.ruff.lint]
extend-select = [
    "D",  # pydocstyle
    "UP",
    "I",
]
